// Generated by Wrangler on Thu Mar 07 2024 20:15:53 GMT+0800 (China Standard Time)
// by running `wrangler types`

export {}
declare global {
  const KV_STORE: KVNamespace
  const R2_BUCKET: R2Bucket
}
