account_id = "0db3c9ec1d741afb9a63eab399c77c3b"
name = "starter-vike-cloudflare-react-worker"
main = "./src/worker/index.ts"
compatibility_flags = [ "streams_enable_constructors" ]
compatibility_date = "2021-09-29"
workers_dev = true

[site]
bucket = "./dist/client"

[dev]
port = 3000
