account_id = "0db3c9ec1d741afb9a63eab399c77c3b"
name = "starter-vike-cloudflare-react-worker"
main = "./src/worker/index.ts"
compatibility_flags = [ "streams_enable_constructors" ]
compatibility_date = "2021-09-29"
workers_dev = true
kv_namespaces = [ { binding = "KV_STORE", id = "d3db85d6f7b14a338feda4cc0235e165" } ]

[vars]
ENABLED_R2 = true

[env.production.vars]
ENABLED_R2 = false

[site]
bucket = "./dist/client"

[dev]
port = 3000

[[r2_buckets]]
binding = 'R2_BUCKET'
bucket_name = 'starter-vike-cloudflare-react-worker'
preview_bucket_name = 'starter-vike-cloudflare-react-worker'
